version: '3.8'

services:
  web:
    build:
      context: . # Build from the current directory, where Dockerfile is located
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - '8000:8000' # Map the host's port 8000 to the container's port 8000
    volumes:
      - .:/app # Map the current directory to the /app directory in the container
